version: '3'
services:
  etl:
    build:
      context: ./apps/salvo-matteini-etl
    env_file:
      - .env
    tty: true
    command: >
      salvo-matteini-etl
  mongo:
    image: mongo:latest
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./volumes/mongo/mongodata:/data/db
    #      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    #    environment:
    #      MONGO_INITDB_ROOT_USERNAME: admin
    #      MONGO_INITDB_ROOT_PASSWORD: admin
    #      MONGO_INITDB_DATABASE: tweets
  bot:
    build:
      context: ./apps/salvo-matteini-bot
    env_file:
      - .env
    tty: true
    command: >
      salvo-matteini-bot
    volumes:
      - ./input:/input
      - ./output:/output
      - /tmp:/tmp
