version: '3'
services:
  python:
    build: .
    tty: true
    volumes:
      - ./app:/usr/local/app
      - ./volumes/logs/cron.log:/var/log/cron.log
    # command: >
    #     sh -c "python download_tweets.py"
  mongo:
    image: webhippie/mongodb:latest
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - ./volumes/mongodata:/var/lib/mongodb/db
      # - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      # MONGODB_AUTH: true
      MONGODB_AUTH_DB: admin
      MONGODB_DATABASE: admin
      MONGODB_DBPATH: /var/lib/mongodb/db
      # MONGODB_USERNAME: admin
      # MONGODB_PASSWORD: admin
      MONGODB_ROOT_PASSWORD: admin
      MONGODB_ROOT_USERNAME: admin

